[meta]
  title = "Java Transcription Starter"
  description = "Get started using Deepgram's Transcription with this Java demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "Java"

[build]
  command = "mvn compile"

[config]
  sample = ".env-sample"
  output = ".env"

[post-build]
  message = "mvn exec:java -Dexec.mainClass=App"
