[meta]
  title = "Pre-recorded Transcription Java Starter"
  description = "Basic demo for using Deepgram to transcribe files with Java"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "Java"

[build]
  command = "mvn compile"

[config]
  sample = ".env-sample"
  output = ".env"

[post-build]
  message = "mvn exec:java -Dexec.mainClass=App"
